### ISSUE TITLE
Site crash on 0 input in Daily Cost

### ISSUE THREAD

**Issue by Divyanshsingh1910** [Ashu3208/MessAutomationSystem#37]
Let's say the admin enters this Dues
![image](https://user-images.githubusercontent.com/103668090/230604375-d3e03be7-9ccf-4f54-b84b-83c041e6f925.png)
Now if we click submit, this shows up
![image](https://user-images.githubusercontent.com/103668090/230604432-ba6b74da-1c77-4748-8ca0-b83135a5a5fc.png)

**Comment by Ashu3208** [comment]
Resolved

**Comment by divc13** [comment]
I think the error is still not resolved. I am getting the same error message.

![image](https://user-images.githubusercontent.com/110289042/230658261-440d4e21-9356-42ca-8b22-5b51aeaca676.png)

![image](https://user-images.githubusercontent.com/110289042/230658272-80e565ba-bf15-4696-8068-0c24411080c5.png)

This is probably because one of the dates is in the past.

**Comment by Ashu3208** [comment]
This was because the min value for daily cost should be 1. I have resolved the issue now.
